//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomRepoMgr.Core.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RomRepoMgr.Core.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Base32_Not_enought_data {
            get {
                return ResourceManager.GetString("Base32_Not_enought_data", resourceCulture);
            }
        }
        
        internal static string Base32_Invalid_format {
            get {
                return ResourceManager.GetString("Base32_Invalid_format", resourceCulture);
            }
        }
        
        internal static string Cannot_seek_before_start {
            get {
                return ResourceManager.GetString("Cannot_seek_before_start", resourceCulture);
            }
        }
        
        internal static string Cannot_seek_after_end {
            get {
                return ResourceManager.GetString("Cannot_seek_after_end", resourceCulture);
            }
        }
        
        internal static string Spamsum_no_binary {
            get {
                return ResourceManager.GetString("Spamsum_no_binary", resourceCulture);
            }
        }
        
        internal static string Assertion_failed {
            get {
                return ResourceManager.GetString("Assertion_failed", resourceCulture);
            }
        }
        
        internal static string Spamsum_Input_exceeds_data {
            get {
                return ResourceManager.GetString("Spamsum_Input_exceeds_data", resourceCulture);
            }
        }
        
        internal static string Not_yet_implemented {
            get {
                return ResourceManager.GetString("Not_yet_implemented", resourceCulture);
            }
        }
        
        internal static string DatabaseFileExistsMsgBoxTitle {
            get {
                return ResourceManager.GetString("DatabaseFileExistsMsgBoxTitle", resourceCulture);
            }
        }
        
        internal static string UnArPathNotSet {
            get {
                return ResourceManager.GetString("UnArPathNotSet", resourceCulture);
            }
        }
        
        internal static string CannotFindUnArAtPath {
            get {
                return ResourceManager.GetString("CannotFindUnArAtPath", resourceCulture);
            }
        }
        
        internal static string CannotFindLsAr {
            get {
                return ResourceManager.GetString("CannotFindLsAr", resourceCulture);
            }
        }
        
        internal static string CannotRunUnAr {
            get {
                return ResourceManager.GetString("CannotRunUnAr", resourceCulture);
            }
        }
        
        internal static string CannotRunLsAr {
            get {
                return ResourceManager.GetString("CannotRunLsAr", resourceCulture);
            }
        }
        
        internal static string NotCorrectUnAr {
            get {
                return ResourceManager.GetString("NotCorrectUnAr", resourceCulture);
            }
        }
        
        internal static string NotCorrectLsAr {
            get {
                return ResourceManager.GetString("NotCorrectLsAr", resourceCulture);
            }
        }
        
        internal static string ParsinDatFile {
            get {
                return ResourceManager.GetString("ParsinDatFile", resourceCulture);
            }
        }
        
        internal static string HashingDatFile {
            get {
                return ResourceManager.GetString("HashingDatFile", resourceCulture);
            }
        }
        
        internal static string DatAlreadyInDatabase {
            get {
                return ResourceManager.GetString("DatAlreadyInDatabase", resourceCulture);
            }
        }
        
        internal static string AddingDatToDatabase {
            get {
                return ResourceManager.GetString("AddingDatToDatabase", resourceCulture);
            }
        }
        
        internal static string CompressingDatFile {
            get {
                return ResourceManager.GetString("CompressingDatFile", resourceCulture);
            }
        }
        
        internal static string GettingMachineNames {
            get {
                return ResourceManager.GetString("GettingMachineNames", resourceCulture);
            }
        }
        
        internal static string AddingMachines {
            get {
                return ResourceManager.GetString("AddingMachines", resourceCulture);
            }
        }
        
        internal static string SavingChangesToDatabase {
            get {
                return ResourceManager.GetString("SavingChangesToDatabase", resourceCulture);
            }
        }
        
        internal static string RetrievingRomsAndDisks {
            get {
                return ResourceManager.GetString("RetrievingRomsAndDisks", resourceCulture);
            }
        }
        
        internal static string AddingRoms {
            get {
                return ResourceManager.GetString("AddingRoms", resourceCulture);
            }
        }
        
        internal static string FoundRomWithoutMachine {
            get {
                return ResourceManager.GetString("FoundRomWithoutMachine", resourceCulture);
            }
        }
        
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        internal static string RetrievingRomSetFromDatabase {
            get {
                return ResourceManager.GetString("RetrievingRomSetFromDatabase", resourceCulture);
            }
        }
        
        internal static string CouldNotFindRomSetInDatabase {
            get {
                return ResourceManager.GetString("CouldNotFindRomSetInDatabase", resourceCulture);
            }
        }
        
        internal static string ExportingRoms {
            get {
                return ResourceManager.GetString("ExportingRoms", resourceCulture);
            }
        }
        
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        internal static string CannotFindZipEntryInDictionary {
            get {
                return ResourceManager.GetString("CannotFindZipEntryInDictionary", resourceCulture);
            }
        }
        
        internal static string CannotFindHashInRepository {
            get {
                return ResourceManager.GetString("CannotFindHashInRepository", resourceCulture);
            }
        }
        
        internal static string Compressing {
            get {
                return ResourceManager.GetString("Compressing", resourceCulture);
            }
        }
        
        internal static string EnumeratingFiles {
            get {
                return ResourceManager.GetString("EnumeratingFiles", resourceCulture);
            }
        }
        
        internal static string Importing {
            get {
                return ResourceManager.GetString("Importing", resourceCulture);
            }
        }
        
        internal static string CheckingIfFIleIsAnArchive {
            get {
                return ResourceManager.GetString("CheckingIfFIleIsAnArchive", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string ErrorWithMessage {
            get {
                return ResourceManager.GetString("ErrorWithMessage", resourceCulture);
            }
        }
        
        internal static string ExtractingArchive {
            get {
                return ResourceManager.GetString("ExtractingArchive", resourceCulture);
            }
        }
        
        internal static string RemovingTemporaryPath {
            get {
                return ResourceManager.GetString("RemovingTemporaryPath", resourceCulture);
            }
        }
        
        internal static string ExtractedContents {
            get {
                return ResourceManager.GetString("ExtractedContents", resourceCulture);
            }
        }
        
        internal static string HashingFile {
            get {
                return ResourceManager.GetString("HashingFile", resourceCulture);
            }
        }
        
        internal static string UnknownFile {
            get {
                return ResourceManager.GetString("UnknownFile", resourceCulture);
            }
        }
        
        internal static string CompressingFile {
            get {
                return ResourceManager.GetString("CompressingFile", resourceCulture);
            }
        }
        
        internal static string Finishing {
            get {
                return ResourceManager.GetString("Finishing", resourceCulture);
            }
        }
        
        internal static string UnhandledExceptionWhenImporting {
            get {
                return ResourceManager.GetString("UnhandledExceptionWhenImporting", resourceCulture);
            }
        }
        
        internal static string AddingDisks {
            get {
                return ResourceManager.GetString("AddingDisks", resourceCulture);
            }
        }
        
        internal static string FoundDiskWithoutMachine {
            get {
                return ResourceManager.GetString("FoundDiskWithoutMachine", resourceCulture);
            }
        }
        
        internal static string NotAChdFile {
            get {
                return ResourceManager.GetString("NotAChdFile", resourceCulture);
            }
        }
        
        internal static string NoChecksumsFound {
            get {
                return ResourceManager.GetString("NoChecksumsFound", resourceCulture);
            }
        }
    }
}
