//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomRepoMgr.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RomRepoMgr.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string FileMenuText {
            get {
                return ResourceManager.GetString("FileMenuText", resourceCulture);
            }
        }
        
        public static string RomSets {
            get {
                return ResourceManager.GetString("RomSets", resourceCulture);
            }
        }
        
        public static string RomSetNameLabel {
            get {
                return ResourceManager.GetString("RomSetNameLabel", resourceCulture);
            }
        }
        
        public static string RomSetVersionLabel {
            get {
                return ResourceManager.GetString("RomSetVersionLabel", resourceCulture);
            }
        }
        
        public static string RomSetAuthorLabel {
            get {
                return ResourceManager.GetString("RomSetAuthorLabel", resourceCulture);
            }
        }
        
        public static string RomSetDateLabel {
            get {
                return ResourceManager.GetString("RomSetDateLabel", resourceCulture);
            }
        }
        
        public static string RomSetDescriptionLabel {
            get {
                return ResourceManager.GetString("RomSetDescriptionLabel", resourceCulture);
            }
        }
        
        public static string RomSetCommentLabel {
            get {
                return ResourceManager.GetString("RomSetCommentLabel", resourceCulture);
            }
        }
        
        public static string RomSetTotalMachinesLabel {
            get {
                return ResourceManager.GetString("RomSetTotalMachinesLabel", resourceCulture);
            }
        }
        
        public static string RomSetCompleteMachinesLabel {
            get {
                return ResourceManager.GetString("RomSetCompleteMachinesLabel", resourceCulture);
            }
        }
        
        public static string RomSetIncompleteMachinesLabel {
            get {
                return ResourceManager.GetString("RomSetIncompleteMachinesLabel", resourceCulture);
            }
        }
        
        public static string RomSetTotalRomsLabel {
            get {
                return ResourceManager.GetString("RomSetTotalRomsLabel", resourceCulture);
            }
        }
        
        public static string RomSetHaveRomsLabel {
            get {
                return ResourceManager.GetString("RomSetHaveRomsLabel", resourceCulture);
            }
        }
        
        public static string RomSetMissRomsLabel {
            get {
                return ResourceManager.GetString("RomSetMissRomsLabel", resourceCulture);
            }
        }
        
        public static string FileMenuImportDatFileText {
            get {
                return ResourceManager.GetString("FileMenuImportDatFileText", resourceCulture);
            }
        }
        
        public static string FileMenuImportDatFolderText {
            get {
                return ResourceManager.GetString("FileMenuImportDatFolderText", resourceCulture);
            }
        }
        
        public static string FileMenuSettingsText {
            get {
                return ResourceManager.GetString("FileMenuSettingsText", resourceCulture);
            }
        }
        
        public static string FileMenuExitText {
            get {
                return ResourceManager.GetString("FileMenuExitText", resourceCulture);
            }
        }
        
        public static string FilesystemMenuText {
            get {
                return ResourceManager.GetString("FilesystemMenuText", resourceCulture);
            }
        }
        
        public static string FilesystemMenuMountText {
            get {
                return ResourceManager.GetString("FilesystemMenuMountText", resourceCulture);
            }
        }
        
        public static string RomsMenuText {
            get {
                return ResourceManager.GetString("RomsMenuText", resourceCulture);
            }
        }
        
        public static string RomsMenuImportText {
            get {
                return ResourceManager.GetString("RomsMenuImportText", resourceCulture);
            }
        }
        
        public static string RomSetsMenuText {
            get {
                return ResourceManager.GetString("RomSetsMenuText", resourceCulture);
            }
        }
        
        public static string RomSetsMenuSaveRomsText {
            get {
                return ResourceManager.GetString("RomSetsMenuSaveRomsText", resourceCulture);
            }
        }
        
        public static string RomSetsMenuSaveDatText {
            get {
                return ResourceManager.GetString("RomSetsMenuSaveDatText", resourceCulture);
            }
        }
        
        public static string RomSetsMenuEditText {
            get {
                return ResourceManager.GetString("RomSetsMenuEditText", resourceCulture);
            }
        }
        
        public static string RomSetsMenuDeleteText {
            get {
                return ResourceManager.GetString("RomSetsMenuDeleteText", resourceCulture);
            }
        }
        
        public static string HelpMenuText {
            get {
                return ResourceManager.GetString("HelpMenuText", resourceCulture);
            }
        }
        
        public static string HelpMenuAboutText {
            get {
                return ResourceManager.GetString("HelpMenuAboutText", resourceCulture);
            }
        }
        
        public static string AboutLabel {
            get {
                return ResourceManager.GetString("AboutLabel", resourceCulture);
            }
        }
        
        public static string LibrariesLabel {
            get {
                return ResourceManager.GetString("LibrariesLabel", resourceCulture);
            }
        }
        
        public static string AuthorsLabel {
            get {
                return ResourceManager.GetString("AuthorsLabel", resourceCulture);
            }
        }
        
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        public static string LicenseLabel {
            get {
                return ResourceManager.GetString("LicenseLabel", resourceCulture);
            }
        }
        
        public static string CloseLabel {
            get {
                return ResourceManager.GetString("CloseLabel", resourceCulture);
            }
        }
        
        public static string AssembliesLibraryText {
            get {
                return ResourceManager.GetString("AssembliesLibraryText", resourceCulture);
            }
        }
        
        public static string AssembliesVersionText {
            get {
                return ResourceManager.GetString("AssembliesVersionText", resourceCulture);
            }
        }
        
        public static string AuthorsText {
            get {
                return ResourceManager.GetString("AuthorsText", resourceCulture);
            }
        }
        
        public static string HomepageLabel {
            get {
                return ResourceManager.GetString("HomepageLabel", resourceCulture);
            }
        }
        
        public static string TotalMachinesLabel {
            get {
                return ResourceManager.GetString("TotalMachinesLabel", resourceCulture);
            }
        }
        
        public static string CompleteMachinesLabel {
            get {
                return ResourceManager.GetString("CompleteMachinesLabel", resourceCulture);
            }
        }
        
        public static string IncompleteMachinesLabel {
            get {
                return ResourceManager.GetString("IncompleteMachinesLabel", resourceCulture);
            }
        }
        
        public static string TotalRomsLabel {
            get {
                return ResourceManager.GetString("TotalRomsLabel", resourceCulture);
            }
        }
        
        public static string HaveRomsLabel {
            get {
                return ResourceManager.GetString("HaveRomsLabel", resourceCulture);
            }
        }
        
        public static string MissRomsLabel {
            get {
                return ResourceManager.GetString("MissRomsLabel", resourceCulture);
            }
        }
        
        public static string EditDatTitle {
            get {
                return ResourceManager.GetString("EditDatTitle", resourceCulture);
            }
        }
        
        public static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        public static string ExportDatTitle {
            get {
                return ResourceManager.GetString("ExportDatTitle", resourceCulture);
            }
        }
        
        public static string DecompressingDat {
            get {
                return ResourceManager.GetString("DecompressingDat", resourceCulture);
            }
        }
        
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        public static string ExportRomsTitle {
            get {
                return ResourceManager.GetString("ExportRomsTitle", resourceCulture);
            }
        }
        
        public static string PathLabel {
            get {
                return ResourceManager.GetString("PathLabel", resourceCulture);
            }
        }
        
        public static string AllFilesLabel {
            get {
                return ResourceManager.GetString("AllFilesLabel", resourceCulture);
            }
        }
        
        public static string RecursiveLabel {
            get {
                return ResourceManager.GetString("RecursiveLabel", resourceCulture);
            }
        }
        
        public static string ImportDatFolderTitle {
            get {
                return ResourceManager.GetString("ImportDatFolderTitle", resourceCulture);
            }
        }
        
        public static string ResultFilenameLabel {
            get {
                return ResourceManager.GetString("ResultFilenameLabel", resourceCulture);
            }
        }
        
        public static string ResultStatusLabel {
            get {
                return ResourceManager.GetString("ResultStatusLabel", resourceCulture);
            }
        }
        
        public static string StartLabel {
            get {
                return ResourceManager.GetString("StartLabel", resourceCulture);
            }
        }
        
        public static string SearchingForFiles {
            get {
                return ResourceManager.GetString("SearchingForFiles", resourceCulture);
            }
        }
        
        public static string FoundFiles {
            get {
                return ResourceManager.GetString("FoundFiles", resourceCulture);
            }
        }
        
        public static string ImportingItem {
            get {
                return ResourceManager.GetString("ImportingItem", resourceCulture);
            }
        }
        
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        public static string ImportDatTitle {
            get {
                return ResourceManager.GetString("ImportDatTitle", resourceCulture);
            }
        }
        
        public static string RemoveFilesLabel {
            get {
                return ResourceManager.GetString("RemoveFilesLabel", resourceCulture);
            }
        }
        
        public static string KnownOnlyLabel {
            get {
                return ResourceManager.GetString("KnownOnlyLabel", resourceCulture);
            }
        }
        
        public static string RecurseArchivesLabel {
            get {
                return ResourceManager.GetString("RecurseArchivesLabel", resourceCulture);
            }
        }
        
        public static string ImportRomFolderTitle {
            get {
                return ResourceManager.GetString("ImportRomFolderTitle", resourceCulture);
            }
        }
        
        public static string RemoveDatTitle {
            get {
                return ResourceManager.GetString("RemoveDatTitle", resourceCulture);
            }
        }
        
        public static string RetrievingRomSetFromDatabase {
            get {
                return ResourceManager.GetString("RetrievingRomSetFromDatabase", resourceCulture);
            }
        }
        
        public static string RemovingRomSetFromDatabase {
            get {
                return ResourceManager.GetString("RemovingRomSetFromDatabase", resourceCulture);
            }
        }
        
        public static string SavingChangesToDatabase {
            get {
                return ResourceManager.GetString("SavingChangesToDatabase", resourceCulture);
            }
        }
        
        public static string RemovingDatFileFromRepo {
            get {
                return ResourceManager.GetString("RemovingDatFileFromRepo", resourceCulture);
            }
        }
        
        public static string ChooseLabel {
            get {
                return ResourceManager.GetString("ChooseLabel", resourceCulture);
            }
        }
        
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        public static string DatabaseFileLabel {
            get {
                return ResourceManager.GetString("DatabaseFileLabel", resourceCulture);
            }
        }
        
        public static string RepositoryFolderLabel {
            get {
                return ResourceManager.GetString("RepositoryFolderLabel", resourceCulture);
            }
        }
        
        public static string TemporaryFolderLabel {
            get {
                return ResourceManager.GetString("TemporaryFolderLabel", resourceCulture);
            }
        }
        
        public static string UnArPathLabel {
            get {
                return ResourceManager.GetString("UnArPathLabel", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string TheUnarchiverVersionLabel {
            get {
                return ResourceManager.GetString("TheUnarchiverVersionLabel", resourceCulture);
            }
        }
        
        public static string ChooseUnArExecutable {
            get {
                return ResourceManager.GetString("ChooseUnArExecutable", resourceCulture);
            }
        }
        
        public static string ChooseTemporaryFolder {
            get {
                return ResourceManager.GetString("ChooseTemporaryFolder", resourceCulture);
            }
        }
        
        public static string ChooseRepositoryFolder {
            get {
                return ResourceManager.GetString("ChooseRepositoryFolder", resourceCulture);
            }
        }
        
        public static string ChooseDatabaseFile {
            get {
                return ResourceManager.GetString("ChooseDatabaseFile", resourceCulture);
            }
        }
        
        public static string DatabaseFileMsgBoxTryOpen {
            get {
                return ResourceManager.GetString("DatabaseFileMsgBoxTryOpen", resourceCulture);
            }
        }
        
        public static string DatabaseFileTryOpenCaption {
            get {
                return ResourceManager.GetString("DatabaseFileTryOpenCaption", resourceCulture);
            }
        }
        
        public static string DatabaseFileExistsMsgBoxTitle {
            get {
                return ResourceManager.GetString("DatabaseFileExistsMsgBoxTitle", resourceCulture);
            }
        }
        
        public static string DatabaseFileUnusableMsgBoxTitle {
            get {
                return ResourceManager.GetString("DatabaseFileUnusableMsgBoxTitle", resourceCulture);
            }
        }
        
        public static string DatabaseFileUnusableDeleteMsgBoxCaption {
            get {
                return ResourceManager.GetString("DatabaseFileUnusableDeleteMsgBoxCaption", resourceCulture);
            }
        }
        
        public static string DatabaseFileUnusableMsgBoxCaption {
            get {
                return ResourceManager.GetString("DatabaseFileUnusableMsgBoxCaption", resourceCulture);
            }
        }
        
        public static string DatabaseFileDeleteCaption {
            get {
                return ResourceManager.GetString("DatabaseFileDeleteCaption", resourceCulture);
            }
        }
        
        public static string DatabaseFileCannotDeleteTitle {
            get {
                return ResourceManager.GetString("DatabaseFileCannotDeleteTitle", resourceCulture);
            }
        }
        
        public static string DatabaseFileCannotDeleteCaption {
            get {
                return ResourceManager.GetString("DatabaseFileCannotDeleteCaption", resourceCulture);
            }
        }
        
        public static string ImportDatFileDialogTitle {
            get {
                return ResourceManager.GetString("ImportDatFileDialogTitle", resourceCulture);
            }
        }
        
        public static string DatFilesDialogLabel {
            get {
                return ResourceManager.GetString("DatFilesDialogLabel", resourceCulture);
            }
        }
        
        public static string AllFilesDialogLabel {
            get {
                return ResourceManager.GetString("AllFilesDialogLabel", resourceCulture);
            }
        }
        
        public static string ImportDatFolderDialogTitle {
            get {
                return ResourceManager.GetString("ImportDatFolderDialogTitle", resourceCulture);
            }
        }
        
        public static string ImportRomsFolderDialogTitle {
            get {
                return ResourceManager.GetString("ImportRomsFolderDialogTitle", resourceCulture);
            }
        }
        
        public static string DeleteRomSetMsgBoxTitle {
            get {
                return ResourceManager.GetString("DeleteRomSetMsgBoxTitle", resourceCulture);
            }
        }
        
        public static string DeleteRomSetMsgBoxCaption {
            get {
                return ResourceManager.GetString("DeleteRomSetMsgBoxCaption", resourceCulture);
            }
        }
        
        public static string ExportRomsDialogTitle {
            get {
                return ResourceManager.GetString("ExportRomsDialogTitle", resourceCulture);
            }
        }
        
        public static string SelectMountPointDialogTitle {
            get {
                return ResourceManager.GetString("SelectMountPointDialogTitle", resourceCulture);
            }
        }
        
        public static string LoadingSettingsText {
            get {
                return ResourceManager.GetString("LoadingSettingsText", resourceCulture);
            }
        }
        
        public static string CheckingUnArText {
            get {
                return ResourceManager.GetString("CheckingUnArText", resourceCulture);
            }
        }
        
        public static string LoadingDatabaseText {
            get {
                return ResourceManager.GetString("LoadingDatabaseText", resourceCulture);
            }
        }
        
        public static string MigratingDatabaseText {
            get {
                return ResourceManager.GetString("MigratingDatabaseText", resourceCulture);
            }
        }
        
        public static string LoadingRomSetsText {
            get {
                return ResourceManager.GetString("LoadingRomSetsText", resourceCulture);
            }
        }
        
        public static string ExitButtonText {
            get {
                return ResourceManager.GetString("ExitButtonText", resourceCulture);
            }
        }
        
        public static string FilesystemMenuUmountText {
            get {
                return ResourceManager.GetString("FilesystemMenuUmountText", resourceCulture);
            }
        }
        
        public static string RomSetCategoryLabel {
            get {
                return ResourceManager.GetString("RomSetCategoryLabel", resourceCulture);
            }
        }
        
        public static string DatabaseMenuText {
            get {
                return ResourceManager.GetString("DatabaseMenuText", resourceCulture);
            }
        }
        
        public static string DatabaseMenuUpdateStatsText {
            get {
                return ResourceManager.GetString("DatabaseMenuUpdateStatsText", resourceCulture);
            }
        }
        
        public static string UpdateStatsConfirmationDialogText {
            get {
                return ResourceManager.GetString("UpdateStatsConfirmationDialogText", resourceCulture);
            }
        }
        
        public static string UpdateStatsTitle {
            get {
                return ResourceManager.GetString("UpdateStatsTitle", resourceCulture);
            }
        }
        
        public static string CalculatingStatisticsForRomSet {
            get {
                return ResourceManager.GetString("CalculatingStatisticsForRomSet", resourceCulture);
            }
        }
        
        public static string RemovingOldStatistics {
            get {
                return ResourceManager.GetString("RemovingOldStatistics", resourceCulture);
            }
        }
        
        public static string RetrievingRomSetsFromDatabase {
            get {
                return ResourceManager.GetString("RetrievingRomSetsFromDatabase", resourceCulture);
            }
        }
        
        public static string NativeMenuPreferencesText {
            get {
                return ResourceManager.GetString("NativeMenuPreferencesText", resourceCulture);
            }
        }
        
        public static string NativeMenuQuitText {
            get {
                return ResourceManager.GetString("NativeMenuQuitText", resourceCulture);
            }
        }
    }
}
