//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomRepoMgr.Blazor.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RomRepoMgr.Blazor.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ROMs_will_be_imported_from {
            get {
                return ResourceManager.GetString("ROMs_will_be_imported_from", resourceCulture);
            }
        }
        
        public static string RemoveFilesLabel {
            get {
                return ResourceManager.GetString("RemoveFilesLabel", resourceCulture);
            }
        }
        
        public static string KnownOnlyLabel {
            get {
                return ResourceManager.GetString("KnownOnlyLabel", resourceCulture);
            }
        }
        
        public static string RecurseArchivesLabel {
            get {
                return ResourceManager.GetString("RecurseArchivesLabel", resourceCulture);
            }
        }
        
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string ImportingItem {
            get {
                return ResourceManager.GetString("ImportingItem", resourceCulture);
            }
        }
        
        public static string ProcessingArchive {
            get {
                return ResourceManager.GetString("ProcessingArchive", resourceCulture);
            }
        }
        
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        public static string DATs_will_be_imported_from {
            get {
                return ResourceManager.GetString("DATs_will_be_imported_from", resourceCulture);
            }
        }
        
        public static string SearchingForFiles {
            get {
                return ResourceManager.GetString("SearchingForFiles", resourceCulture);
            }
        }
        
        public static string RomSetNameLabel {
            get {
                return ResourceManager.GetString("RomSetNameLabel", resourceCulture);
            }
        }
        
        public static string RomSetVersionLabel {
            get {
                return ResourceManager.GetString("RomSetVersionLabel", resourceCulture);
            }
        }
        
        public static string RomSetAuthorLabel {
            get {
                return ResourceManager.GetString("RomSetAuthorLabel", resourceCulture);
            }
        }
        
        public static string RomSetCategoryLabel {
            get {
                return ResourceManager.GetString("RomSetCategoryLabel", resourceCulture);
            }
        }
        
        public static string RomSetDateLabel {
            get {
                return ResourceManager.GetString("RomSetDateLabel", resourceCulture);
            }
        }
        
        public static string RomSetDescriptionLabel {
            get {
                return ResourceManager.GetString("RomSetDescriptionLabel", resourceCulture);
            }
        }
        
        public static string RomSetCommentLabel {
            get {
                return ResourceManager.GetString("RomSetCommentLabel", resourceCulture);
            }
        }
        
        public static string HomepageLabel {
            get {
                return ResourceManager.GetString("HomepageLabel", resourceCulture);
            }
        }
        
        public static string RomSetTotalMachinesLabel {
            get {
                return ResourceManager.GetString("RomSetTotalMachinesLabel", resourceCulture);
            }
        }
        
        public static string RomSetCompleteMachinesLabel {
            get {
                return ResourceManager.GetString("RomSetCompleteMachinesLabel", resourceCulture);
            }
        }
        
        public static string RomSetIncompleteMachinesLabel {
            get {
                return ResourceManager.GetString("RomSetIncompleteMachinesLabel", resourceCulture);
            }
        }
        
        public static string RomSetTotalRomsLabel {
            get {
                return ResourceManager.GetString("RomSetTotalRomsLabel", resourceCulture);
            }
        }
        
        public static string RomSetHaveRomsLabel {
            get {
                return ResourceManager.GetString("RomSetHaveRomsLabel", resourceCulture);
            }
        }
        
        public static string RomSetMissRomsLabel {
            get {
                return ResourceManager.GetString("RomSetMissRomsLabel", resourceCulture);
            }
        }
        
        public static string ImportDats {
            get {
                return ResourceManager.GetString("ImportDats", resourceCulture);
            }
        }
        
        public static string ImportRoms {
            get {
                return ResourceManager.GetString("ImportRoms", resourceCulture);
            }
        }
        
        public static string ExportDat {
            get {
                return ResourceManager.GetString("ExportDat", resourceCulture);
            }
        }
        
        public static string RemoveDat {
            get {
                return ResourceManager.GetString("RemoveDat", resourceCulture);
            }
        }
        
        public static string ExportRoms {
            get {
                return ResourceManager.GetString("ExportRoms", resourceCulture);
            }
        }
    }
}
